services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: drizzle-postgres
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: drizzle-pg
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
