import { Product } from "../seed-functions/generate-products";

export const productsArray: Product[] = [
  {
    id: "431e32eb-9960-4aaf-a4bf-ab144830d546",
    type: "Tempered Glass",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Tempered Glass",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      edgework: "",
      misc: "",
    },
    date_created: "4/27/2023, 11:18:29 PM",
    date_updated: "9/6/2024, 6:27:41 AM",
  },
  {
    id: "362a0e00-a3b2-45f4-bebf-b06a850993b5",
    type: "Insulated Unit/Dual Pane",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Insulated Unit/Dual Pane",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      misc: "",
      spacer: "",
    },
    date_created: "7/7/2024, 8:56:46 PM",
    date_updated: "9/13/2024, 12:12:19 AM",
  },
  {
    id: "634adcdf-a739-4eaf-a653-09f1d403f8da",
    type: "Laminate/Safety Glass",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Laminate/Safety Glass",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      misc: "",
      edgework: "",
      lami_layer: "",
    },
    date_created: "2/25/2024, 9:53:56 AM",
    date_updated: "8/26/2024, 2:23:03 AM",
  },
  {
    id: "d142e971-d28b-4418-ae40-c698f5ac25a0",
    type: "Tempered Laminate",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Tempered Laminate",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      edgework: "",
      misc: "",
    },
    date_created: "5/7/2023, 4:30:21 PM",
    date_updated: "9/6/2024, 10:03:07 PM",
  },
  {
    id: "24a2d78f-642d-4937-ba68-b6f113e57a76",
    type: "Shower Doors/Panels",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Shower Doors/Panels",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      fabrication: "",
      misc: "",
    },
    date_created: "7/25/2024, 5:35:27 PM",
    date_updated: "9/8/2024, 10:17:03 PM",
  },
  {
    id: "670e8f58-76f6-4ade-be60-9f0957456650",
    type: "Annealed Glass",
    image_url: "https://via.placeholder.com/150",
    alt: "alt image description",
    description: "description for Annealed Glass",
    config_options: {
      shape: "",
      dimensions: "",
      thickness: "",
      tint: "",
      fabrication: "",
      misc: "",
    },
    date_created: "4/15/2024, 2:09:08 PM",
    date_updated: "8/25/2024, 6:31:57 AM",
  },
];
